### Put request to put configuration to etcd server
POST http://localhost:8080/api/config?
    key=/DAILY_LIMIT&
    value=500.00
Accept: text/plain

### Get request to get a configuration from etcd server
GET http://localhost:8080/api/config?
    key=/DAILY_LIMIT
Accept: text/plain
